# -*- coding: utf-8 -*-
"""routing_simulator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rqK34HN4GaeYXwjYR-7FcIBzMnhekfsq
"""

graph = {
    'A': [('B', 4), ('C', 1)],
    'B': [('E', 4)],
    'C': [('B', 2), ('D', 4)],
    'D': [('E', 4)],
    'E': []
}

import heapq

def dijkstra(graph, start):
    distances = {node: float('inf') for node in graph}
    distances[start] = 0
    pq = [(0, start)]
    parent = {node: None for node in graph}

    while pq:
        curr_dist, curr_node = heapq.heappop(pq)

        for neighbor, weight in graph[curr_node]:
            distance = curr_dist + weight
            if distance < distances[neighbor]:
                distances[neighbor] = distance
                parent[neighbor] = curr_node
                heapq.heappush(pq, (distance, neighbor))

    return distances, parent

def bellmanford(graph, start):
    distances = {node: float('inf') for node in graph}
    distances[start] = 0
    parent = {node: None for node in graph}

    edges = []
    for node in graph:
        for neighbor, weight in graph[node]:
            edges.append((node, neighbor, weight))

    for _ in range(len(graph) - 1):
        for u, v, w in edges:
            if distances[u] + w < distances[v]:
                distances[v] = distances[u] + w
                parent[v] = u

    return distances, parent

def getpath(parent, target):
    path = []
    while target:
        path.append(target)
        target = parent[target]
    return path[::-1]

start = input("Enter source node: ").strip()
target = input("Enter destination node: ").strip()

ddist, dparent = dijkstra(graph, start)
bdist, bparent = bellmanford(graph, start)

print("Dijkstra:")
print("Cost:", ddist[target])
print("Path:", " -> ".join(getpath(dparent, target)))

print("\nBellman-Ford:")
print("Cost:", bdist[target])
print("Path:", " -> ".join(getpath(bparent, target)))

